extends Node

class_name Enums

enum Suits {SPADE, HEART, CLUB, DIAMOND}
enum SortModes {CUSTOM, VALUES, SUITS}
enum HandRankings {HIGH_CARD, PAIR, TWO_PAIR, THREE_OF_A_KIND, STRAIGHT, FLUSH, FULL_HOUSE, FOUR_OF_A_KIND, STRAIGHT_FLUSH, ROYAL_FLUSH, FIVE_OF_A_KIND, FULL_HOUSE_FLUSH, FIVE_OF_A_KIND_FLUSH}
enum Tiers {TIER_1, TIER_2, TIER_3, TIER_4, BASE}
enum Iterations {BASE, FIRST, SECOND, THIRD, FOURTH}

enum PlayerCharacters { NONE, SAINT_BERNARD, ROTTWEILER, FOXHOUND }

enum RewardsTypes { MOVES, ARTIFACTS, HAND_MANIPULATIONS, HEAL } 

enum CardLocations { DECK, DISCARD_PILE, OWN_HAND, OTHER_HANDS}

enum Slots { FRONT_ROW, MID_ROW, BACK_ROW }
